# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interpolação Linear
#' 
#' Realiza interpolação linear em uma grade bidimensional de valores
#' 
#' @param yData,zData valores da variável explicativa e dependente, respectivamente, na grade
#' @param yPred valores da variável explicativa a interpolar na grade
#' 
#' @return vetor de valores interpolados
INTERPLIN <- function(yData, zData, yPred) {
    .Call('_perdaprodvar_INTERPLIN', PACKAGE = 'perdaprodvar', yData, zData, yPred)
}

#' Interpolação Bilinear
#' 
#' Realiza interpolação bilinear em uma grade tridimensional de valores
#' 
#' @param xData,yData,zData valores das variáveis explicativas (x e y) e dependente (z), na grade
#' @param xPred,yPred valores das variáveis explicativas a interpolar na grade
#' 
#' @return vetor de valores interpolados
INTERPBILIN <- function(xData, yData, zData, xPred, yPred) {
    .Call('_perdaprodvar_INTERPBILIN', PACKAGE = 'perdaprodvar', xData, yData, zData, xPred, yPred)
}

